server:
    port: 8002
spring:
#    datasource:
#        username: root
#        password: rootpass
#        url: jdbc:mysql://localhost:3306/shortlink_db?useSSL=true&serverTimezone=UTC
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        hikari:
#            connection-test-query: select 1
#            connection-timeout: 20000
#            idle-timeout: 300000
#            maximum-pool-size: 5
#            minimum-idle: 5
    datasource:
        # ShardingSphere customizes the Driver to implement hidden logic for database and table sharding
        driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
        # Path to the ShardingSphere configuration file
        url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    data:
        redis:
            host: 127.0.0.1
            port: 6379

logging:
    level:
        com.fran.shortlink.admin.dao.mapper: debug
        com.baomidou.mybatisplus: debug

