dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootpass

rules:
  - !SHARDING
    tables:
      t_user:
        # Actual data nodes, meaning the real database sources and the actual tables inside the databases
        actualDataNodes: ds_0.t_user_${0..15}
        # Table sharding strategy
        tableStrategy:
          # Standard sharding scenario using a single sharding key
          standard:
            # Sharding key
            shardingColumn: username
            # Sharding algorithm, corresponds to rules[0].shardingAlgorithms
            shardingAlgorithmName: user_table_hash_mod
    # Sharding algorithms
    shardingAlgorithms:
      # Sharding algorithm for the user table
      user_table_hash_mod:
        # Shard based on the hash value of the sharding key
        type: HASH_MOD
        # Number of shards
        props:
          sharding-count: 16
# Show both logical SQL and actual SQL
props:
  sql-show: true