dataSources:
    ds_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/shortlink_db?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: rootpass

rules:
    - !SHARDING
        tables:
            t_user:
                # Actual data nodes, meaning the real database sources and the actual tables inside the databases
                actualDataNodes: ds_0.t_user_${0..15}
                # Table sharding strategy
                tableStrategy:
                    # Standard sharding scenario using a single sharding key
                    standard:
                        # Sharding key
                        shardingColumn: username
                        # Sharding algorithm, corresponds to rules[0].shardingAlgorithms
                        shardingAlgorithmName: user_table_hash_mod
        # Sharding algorithms
        shardingAlgorithms:
            # Sharding algorithm for the user table
            user_table_hash_mod:
                # Shard based on the hash value of the sharding key
                type: HASH_MOD
                # Number of shards
                props:
                    sharding-count: 16

    # Data encryption storage rules
    - !ENCRYPT
        # Collection of tables that require encryption
        tables:
            # User table
            t_user:
                # Which fields in the user table need to be encrypted
                columns:
                    # Phone number field (logical field, may not physically exist in the DB)
                    phone:
                        # The real database field where the encrypted phone number is stored
                        cipherColumn: phone
                        # Encryption algorithm used for the phone number
                        encryptorName: common_encryptor
                    email:
                        cipherColumn: email
                        encryptorName: common_encryptor
                # Whether to query using the cipher (encrypted) column
                queryWithCipherColumn: true
        # Encryption algorithms
        encryptors:
            # Custom encryption algorithm name
            common_encryptor:
                # Type of encryption algorithm
                type: AES
                props:
                    # AES encryption key
                    aes-key-value: d6oadClrrb9A3GWo

# Show both logical SQL and actual SQL
props:
    sql-show: true